version: '3'

services:
  bot:
    image: alexander4127/bot-deploy
    labels:
      - "com.centurylinklabs.watchtower.scope=myscope"
    environment:
      BOT_TOKEN: ''
      API_KEY: ''

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 10 --scope myscope
    labels:
      - "com.centurylinklabs.watchtower.scope=myscope"
