name: Trigger deployment on external event

on:
  release:
    types: [ published ]
  create:
  workflow_run:
    workflows: [ "Linter and Docker" ]
    types:
      - completed

jobs:
  deploy:
    name: Deploy a new image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Wait for build to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: main
          check-name: build
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20

      - name: Wait for linter to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: main
          check-name: linter
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bot-deploy:latest
